# Site settings
title: SkytigerNote
#email: nottoobad@126.com
description: > # this means to ignore newlines until "baseurl:"
  Android, kotlin, and some random thought.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skytiger.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  nottoobad

# Build settings
markdown: kramdown
